export enum Events {
  SEND_MESSAGE = 'SEND_MESSAGE',
  RECEIVED_MESSAGE = 'RECEIVED_MESSAGE',
  CREATE_SELF_ROOM = 'CREATE_SELF_ROOM',
  NEW_ACCESS_TOKEN = 'NEW_ACCESS_TOKEN',
  CONNECT = 'connect',
  EXCEPTION = 'exception',
  MESSAGE = 'MESSAGE',
  DISCONNECT = 'disconnect',
  FETCH_NOT_DELIVERED_MESSAGES = 'FETCH_NOT_DELIVERED_MESSAGES',
  RECEIVED_ALL_NOT_DELIVERED_MESSAGES = 'RECEIVED_ALL_NOT_DELIVERED_MESSAGES',
  FETCH_RECIPIENT_ID = 'FETCH_RECIPIENT_ID'
}
