export enum Events {
  CONNECT_USER = 'CONNECT_USER',
  SEND_MESSAGE = 'SEND_MESSAGE',
  RECEIVED_MESSAGE = 'RECEIVED_MESSAGE',
  CREATE_SELF_ROOM = 'CREATE_SELF_ROOM',
  JOIN_ROOM = 'JOIN_ROOM',
  NEW_ACCESS_TOKEN = 'NEW_ACCESS_TOKEN',
  CONNECT = 'connect',
  EXCEPTION = 'exception',
  MESSAGE = 'MESSAGE',
  DISCONNECT = 'disconnect'
}
