export const IDENTITY_KEY_PAIR = 'IDENTITY_KEY_PAIR';
export const REGISTRATION_ID = 'REGISTRATION_ID';
export const PRE_KEYS = 'PRE_KEYS';
export const SIGNED_PRE_KEY = 'SIGNED_PRE_KEY';
export const SESSION_DATA = 'SESSION_DATA';
